#  YML to get jmeter and run it

name: jmeter_notAWS

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps :
     - uses: actions/checkout@v3

     - name: setup-jmeter
       run: |
          java -version  
          sudo wget https://dlcdn.apache.org//jmeter/binaries/apache-jmeter-5.6.2.tgz
          sudo tar -xvf apache-jmeter-5.6.2.tgz
          cd $GITHUB_WORKSPACE/apache-jmeter-5.6.2/bin
          echo "locating jmeter files"
          pwd
          java -jar ApacheJMeter.jar -v
          ps -ef | grep java
     
     - name: download CMD Runner
       run: |
          echo "Downloading CMDRunner"
          cd $GITHUB_WORKSPACE/apache-jmeter-5.6.2/lib
          sudo wget  https://repo1.maven.org/maven2/kg/apc/cmdrunner/2.2/cmdrunner-2.2.jar

     - name: download Plugin Manager
       run: |
          cd $GITHUB_WORKSPACE/apache-jmeter-5.6.2/lib/ext
          sudo wget  https://repo1.maven.org/maven2/kg/apc/jmeter-plugins-manager/1.6/jmeter-plugins-manager-1.6.jar

     - name: install plugins
       run: |
          cd $GITHUB_WORKSPACE/apache-jmeter-5.6.2/lib
          sudo java  -jar cmdrunner-2.2.jar --tool org.jmeterplugins.repository.PluginManagerCMD \
          install-all-except jpgc-hadoop,jpgc-oauth,ulp-jmeter-autocorrelator-plugin,ulp-jmeter-videostreaming-plugin,ulp-jmeter-gwt-plugin,tilln-iso8583

     - name: Look for jmx in directory 
       run: | 
          cd $GITHUB_WORKSPACE/scenarios
          ls -al

     - name: Run JMeter Tests
       run: |
          cd $GITHUB_WORKSPACE/apache-jmeter-5.6.2/bin
          sudo java -jar ApacheJMeter.jar -J-Xms2g -J-Xmx2g J-XX:MaxMetaspaceSize=512m -n \
            -t $GITHUB_WORKSPACE/scenarios/BBC_Demo.jmx \
            -l $GITHUB_WORKSPACE/results/result.csv \
            -q $GITHUB_WORKSPACE/properties/Short_Smoke_Test.properties \
            -o jmeter_report.html

     - name: look for results files
       run: |
         cd $GITHUB_WORKSPACE/apache-jmeter-5.6.2/bin
         ls -alrt
         cd $GITHUB_WORKSPACE/results
         ls -al
       
     - name: Upload csv Results
       uses: actions/upload-artifact@v3
       with:
          name: jmeter-results
          path: /home/runner/work/GHA_Demo/GHA_Demo/results/result.csv   # using WORKSPACE variable does not work

     - name: Upload html Results
       uses: actions/upload-artifact@v3
       with:
          name: jmeter-results-html
          path: /home/runner/work/GHA_Demo/GHA_Demo/results/jmeter_report.html   # using WORKSPACE variable does not work
          
