#  YML to get jmeter and run it

name: jmeter_notAWS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps :
     - uses: actions/checkout@v3

     - name: setup-jmeter

       run: |
          sudo apt-get update
          sudo apt install curl -y
          sudo apt install -y default-jdk
          sudo wget https://dlcdn.apache.org//jmeter/binaries/apache-jmeter-5.6.2.tgz
          sudo tar -xvf apache-jmeter-5.6.2.tgz
          cd $GITHUB_WORKSPACE/apache-jmeter-5.6.2/bin
          echo "locating jmeter files"
          pwd
          ls -al
          java -jar ApacheJMeter.jar -v
          ps -ef | grep java
     

     - name: download CMD Runner

       run: |
          echo "Downloading CMDRunner"
          cd $GITHUB_WORKSPACE/apache-jmeter-5.6.2/lib
          sudo curl -O https://repo1.maven.org/maven2/kg/apc/cmdrunner/2.2/cmdrunner-2.2.jar
          ls -al

     - name: download Plugin Manager

       run: |

          cd $GITHUB_WORKSPACE/apache-jmeter-5.6.2/lib/ext
          sudo curl -O https://repo1.maven.org/maven2/kg/apc/jmeter-plugins-manager/1.6/jmeter-plugins-manager-1.6.jar
          ls -al

     - name: install plugins
       run: |
          cd $GITHUB_WORKSPACE/apache-jmeter-5.6.2/lib
          sudo java  -jar cmdrunner-2.2.jar --tool org.jmeterplugins.repository.PluginManagerCMD install-all-except jpgc-hadoop,jpgc-oauth,ulp-jmeter-autocorrelator-plugin,ulp-jmeter-videostreaming-plugin,ulp-jmeter-gwt-plugin,tilln-iso8583

     - name: Look for jmx in directory 
       run: | 
          cd /home/runner/work/GHA_Demo/GHA_Demo
          ls -al


     - name: Run JMeter Tests

       run: |
          cd $GITHUB_WORKSPACE/apache-jmeter-5.6.2/bin
          sudo ./jmeter.sh -J-Xms2g -J-Xmx2g J-XX:MaxMetaspaceSize=512m -n -t /home/runner/work/GHA_Demo/GHA_Demo/N01_HomepageDemo.jmx -l result.csv
          ls -al

     - name: Upload Results
       uses: actions/upload-artifact@v3
       with:
          name: jmeter-results
          path: /home/runner/work/GHA_Demo/GHA_Demo/apache-jmeter-5.6.2/bin/result.csv
