#  demo use of matrix 
name: demo_matrix
on:
  workflow_dispatch:

jobs:
  matrix_example: 
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        ref_letter: [A,B,C,D]
        index_num: [1,2,3]
      
    steps: 
      - name: Show result
        run: |
          echo "Ref Letter:  " ${{matrix.ref_letter}}
          echo "index num:   "  ${{matrix.index_num}}
