name: Workflow with Input Options

on:
  workflow_dispatch:

env:
  OPTION_1: "Option 1"
  OPTION_2: "Option 2"
  OPTION_3: "Option 3"

        
jobs:
  choose_option:
    runs-on: ubuntu-latest
    steps:
      - name: Choose Option
        id: choose_option
        run: echo "Selected option is ${{ env.SELECTED_OPTION }}"

      - name: Display Chosen Option
        run: echo "Chosen option is ${{ steps.choose_option.outputs.selected_option }}"
