name: Workflow with Input Options

on:
  workflow_dispatch:

env:
  OPTION_1: "Option 1"
  OPTION_2: "Option 2"
  OPTION_3: "Option 3"

        
jobs:
  choose_option:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Display Menu
        run: |
          echo "Select an option:"
          echo "1. Option 1"
          echo "2. Option 2"
          echo "3. Option 3"
          read -p "Enter the number of your choice: " choice

      - name: Process Choice
        run: |
          case $choice in
            1)
              chosen_option="Option 1"
              ;;
            2)
              chosen_option="Option 2"
              ;;
            3)
              chosen_option="Option 3"
              ;;
            *)
              echo "Invalid choice"
              exit 1
              ;;
          esac

      - name: Display Chosen Option
        run: echo "Chosen option is $chosen_option"
