name: Workflow with Input Options

on:
  workflow_dispatch:

    inputs:
      option:
        description: 'Select an option'
        required: true

        # Define the available options as comma-separated values:
        options: |
          -  'Option 1'
          -  'Option 2'
          -  'Option 3'
        default: 'Option 1'
        
jobs:
  choose_option:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Display Chosen Option
        run: echo "Chosen option is ${{ inputs.option }}"
