name: Workflow with Input Options

on:
  workflow_dispatch:

env:
  OPTION_1: "Option 1"
  OPTION_2: "Option 2"
  OPTION_3: "Option 3"

        
jobs:
  choose_option:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Display Chosen Option
        run: echo "Chosen option is ${{ inputs.option }}"
